### ISSUE TITLE
Error and warning while building on kernel 3.19.3

### ISSUE THREAD

**Issue by mdbananapi** [Manouchehri/smi2021#11]
Hi!

I get an set of warnings when trying to build the smi2021 module on my debian banana pi. It has kernel 3.19.3

I do the following steps:
   1. git clone git://github.com/Manouchehri/smi2021.git
   2. cd smi2021/
   3. sed -i '0,/obj/{s/$(CONFIG_VIDEO_SMI2021)/m/}' Makefile # Force building as a module.
   4. make -C /lib/modules/$(uname -r)/build M=$PWD modules

when I run make -C /lib/modules/$(uname -r)/build M=$PWD modules the .ko module is created but I get many warnings like this:

WARNING: "vb2_ioctl_reqbufs" [/home/user1/smi2021-master/smi2021.ko] undefined!
WARNING: "v4l2_event_unsubscribe" [/home/user1/smi2021-master/smi2021.ko] undefined!
WARNING: "video_device_release_empty" [/home/user1/smi2021-master/smi2021.ko] undefined!
...

After I compile the module, I do the following:
   1.mkdir /lib/modules/uname -r/kernel/drivers/media/usb/smi2021
   2.sudo install -Dm644 smi2021.ko mkdir /lib/modules/uname -r/kernel/drivers/media/usb/smi2021
   3.rmmod smi2021
      I get: Error: Module smi2021 is not currently loaded
   4. modprobe smi2021
      I get: ERROR: could not insert 'smi2021': Exec format error

Can you please help me or at least forward into the right direction so I could search for the answer on the internet?

I opened a similar issue with more details at https://github.com/kerpz/smi2021/issues/2

Thanks!

**Comment by Manouchehri** [comment]
Does `make` end successfully or does it quit?

**Comment by mastervolkov** [comment]
Does you follow these part of manual?
...
1. Verify all dependency: 
            "VIDEO_DEV && I2C && SND && USB"
            "SND_PCM" = 
            "VIDEO_SAA711X" = "Device Drivers -> Multimedia support -> Encoders, decoders, sensors and other helper chips -> Philips SAA7111/3/4/5 video decoders"
            "VIDEOBUF2_VMALLOC" (I simple chose in menuconfig: "Device Drivers -> Multimedia support -> Media USB Adapters -> USB Video Class" - it have needed dependency for "VIDEOBUF2_VMALLOC")
...


With you warning like you not have needed modules vb2

**Comment by mdbananapi** [comment]
@ Manouchehri
When I am in the smi2021 directory and I run make, the make command ends successfully and the smi2021.ko file is generated. 

Here is the full output after I run make :

user1@bananapi:~/smi2021$ sudo make
[sudo] password for user1: 
make   -C /lib/modules/3.19.3-bananapi/build M=/home/user1/smi2021 -I/lib/modules/3.19.3-bananapi/build/drivers/media/i2c modules
make[1]: Entering directory `/usr/src/linux-headers-3.19.3-bananapi'
** GIT MODULE VERSION = 6c075ba **
  CC [M]  /home/user1/smi2021/smi2021_main.o
  CC [M]  /home/user1/smi2021/smi2021_bootloader.o
  CC [M]  /home/user1/smi2021/smi2021_v4l2.o
  CC [M]  /home/user1/smi2021/smi2021_audio.o
  LD [M]  /home/user1/smi2021/smi2021.o
  Building modules, stage 2.
** GIT MODULE VERSION = 6c075ba **
  MODPOST 1 modules
WARNING: "vb2_ioctl_reqbufs" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_event_unsubscribe" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "video_device_release_empty" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_ctrl_log_status" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "snd_pcm_period_elapsed" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_device_unregister" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_ctrl_handler_free" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_fop_poll" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_ioctl_streamon" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_ops_wait_prepare" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "__video_register_device" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "snd_pcm_stream_lock" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "snd_pcm_hw_constraint_integer" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_device_register" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_fop_read" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_device_disconnect" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_vmalloc_memops" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_fop_mmap" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_ioctl_qbuf" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "video_unregister_device" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "snd_pcm_set_ops" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_ctrl_subscribe_event" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_plane_vaddr" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_buffer_done" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "snd_pcm_hw_constraint_pow2" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "snd_pcm_lib_ioctl" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_ioctl_dqbuf" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_fop_release" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "video_devdata" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "snd_pcm_stream_unlock" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_fh_open" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "snd_pcm_format_physical_width" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_ioctl_querybuf" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_ctrl_handler_init_class" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_ops_wait_finish" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_i2c_new_subdev_board" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "snd_pcm_new" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_ioctl_streamoff" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_queue_release" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_device_put" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "v4l2_get_timestamp" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "video_ioctl2" [/home/user1/smi2021/smi2021.ko] undefined!
WARNING: "vb2_queue_init" [/home/user1/smi2021/smi2021.ko] undefined!
  CC      /home/user1/smi2021/smi2021.mod.o
  LD [M]  /home/user1/smi2021/smi2021.ko
make[1]: Leaving directory `/usr/src/linux-headers-3.19.3-bananapi'

after this many .o files are generated in the smi2021 folder and the file smi2021.ko is also generated.

**Comment by mdbananapi** [comment]
@mastervolkov

Sorry for asking but how can I verify the dependencies "VIDEO_DEV && I2C && SND && USB"
"SND_PCM" ? 

I have the folder of the debian OS which is currently installed. I have downloaded it from here: http://mirror.igorpecovnik.com/Bananapi_Debian_2.5_wheezy_3.19.3.zip

And when I go to that folder, and run make menuconfig, a menu appears, and I select "Device Drivers -> Multimedia Support" (Has an M letter inside it) but when I look for "Encoders, decoders, sensors and other helper chips" it is not in the list. 

Same for "USB Video Class" it is also not present in "Media USB Adapters". When I go to Device Drivers -> Multimedia Support -> Media USB Adapters" there is nothing to select. it is blank. 

Maybe I need a new version for my kernel? I think it is strange that I do not see these files in kernel 3.19.3 as I have read somewhere that in this version, the SAA7111 driver is included by default.

**Comment by Manouchehri** [comment]
@mdbananapi Try compiling it with a stock wheezy or sid Debian image just so we can narrow down the problem.

**Comment by mastervolkov** [comment]
If you do not see the items, they are **NOT** activated, but you **MUST** activate it!
In `menuconfig` you can press `/` and enter symbol you want (for example: *"VIDEO_SAA711X"*)  
You **must have** `Symbol: VIDEO_SAA711X [=y]` or `Symbol: VIDEO_SAA711X [=m]`.
Also check `Depends on: ` - all symbol in depends **MUST** have *y* or *m*.

Im most case, in blank `Encoders, decoders, sensors and other helper chips` and `Media USB Adapters` - when you not select `Cameras/video grabbers support`.
Also sufficient *UN*select `Autoselect ancillary drivers (tuners, sensors, i2c, frontends)` for view `Encoders, decoders, sensors and other helper chips` in list.

**Comment by mdbananapi** [comment]
I installed the new kernel with the VIDEO_SAA711X activated but I still get those warnings. Maybe I am doing something wrong, or maybe the new kernel or modules have not been installed?

Here is what I did:
1. Download http://mirror.igorpecovnik.com/Bananapi_Debian_2.5_wheezy_3.19.3.zip

2. Extract in folder linux-3.19.3

3. cd to folder linux-3.19.9

4. run make menuconfig

5. Go to Device Drivers/Multimedia Support and unselect "Autoselect ancillary drivers (tuners, sensors, i2c, frontends)" and a new list appears

6. I go to the Encoders, decoders, sensors and other helper chips and press "Y" key to select the needed modules, in my case: Philips SAA7111/3/4/5 video decoders and a few others (I have selected everything in Multimedia Support).

7. I save the configuration as .config in the same folder linux-3.19.3 and exit

8. I run make and it is compiling for about 2 hours

9. I run make modules

10. I run make modules_install

11. I run make install

12. I run reboot

After this I go to the smi2021 folder and do :
1. To clean the old files:
make -C /lib/modules/$(uname -r)/build M=$PWD clean

and after that I do:
make -C /lib/modules/$(uname -r)/build M=$PWD modules
and I still get the workings. Could it be that the VIDEO_SAA711X was not installed?

**Comment by mastervolkov** [comment]
If you build without WARNING's - it is a good.
Must be installed ( and loaded - you can check by `lsmod` command) modules:
* videobuf2-vmalloc
* videobuf2-core

And VIDEO_SAA711X sufficient too.

**Comment by mdbananapi** [comment]
@mastervolkov

When I run lsmod here is what I get:

user1@bananapi:~/linux-3.19.3$ lsmod
Module                  Size  Used by
bnep                    9328  2 
rfcomm                 30147  0 
bluetooth             276808  10 bnep,rfcomm
brcmfmac              151013  0 
brcmutil                4432  1 brcmfmac
ahci_sunxi              2444  0 

I think the videobuf2-vmalloc and videobuf2-core have not installed. Maybe I am not installing the proper way?

**Comment by mastervolkov** [comment]
lsmod not show all installed, they show only running now module.

It is not enough simply to choose module in menuconfig - build and install that modules required too.

**Comment by jonjonarnearne** [comment]
How do load the smi2021 module, do you use `insmod` or `modprobe`?

`insmod` will not load dependencies, while `modprobe` will load the specified module including dependencies.

**Comment by mastervolkov** [comment]
Can you recheck functional from new added commit in `staging` branch?
If so - please, ReRead README - we many change in it.

**Comment by mastervolkov** [comment]
No more unknown warning and error. In master added check dependency on build time and clean errors
