### ISSUE TITLE
Freezes system on Arch

### ISSUE THREAD

**Issue by willghatch** [Manouchehri/smi2021#12]
I just got one of these (SMI-2021CBE), and I run Arch Linux.  I have the 4.1.2-2-ARCH kernel, and I installed the somagic-easycap-smi2021-git AUR package.  When I try to run a video capture with VLC everything freezes up.

**Comment by Manouchehri** [comment]
Have you tried mplayer? I vaguely remember having some issues with VLC.

**Comment by Manouchehri** [comment]
I unfortunately don't have the single channel version anymore to test, but I tried the 4-channel version with VLC and it doesn't seem to crash my system (although it doesn't work as mentioned in #5).

Can you post a log?

**Comment by willghatch** [comment]
Hmm, it's not crashing with mplayer but any options I give it either show nothing but green with some random artifacts or crashes mplayer.  Are there particular settings I need to use?

As far as a log from using vlc, I'm not entirely sure how to get a log -- I assume it's a kernel panic, and the little I've read about getting kernel panic logs seems... like a lot.  If you have any good settings to use for mplayer I'll try them out.  Otherwise, maybe I'll just look for an adapter that has better linux support (I've wasted enough time fussing with this one already).

Thanks for your help.

**Comment by Manouchehri** [comment]
That's sort of odd that you managed to crash the entire system with VLC; you can't do that with mplayer, right?

I don't know the "proper" way to debug kernel logs off the top of my head, but `dmesg -wH > ~/dmesg.log` will probably work decently. Try crashing your system again with VLC and post the last few hundred lines of `~/dmesg.log`.

**Comment by mastervolkov** [comment]
Rewrite some algorithm and add some extended check for fix memory problem.
