### ISSUE TITLE
saa7115 chip 0x94 is unknown.

### ISSUE THREAD

**Issue by mastervolkov** [Manouchehri/smi2021#15]
I load saa7115 with debug:
`modprobe saa7115 debug=1` and my dmesg show:

```saa7115 0-004a: chip 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 11 @ 0x94 is unknown.```

- kernel: 3.17.7-gentoo
- distrib: gentoo
- arch: intel x86_64

What can i do? Which additional info/registry settings need for detect what wrong with my chip?
Or need test any custom patch to saa7115 (test-hrdcode what chip is gm7115)? Or need disasemble box with easycap and public chip photo?

**Comment by jonjonarnearne** [comment]
Hi, Just tested with my device, I get this:
```
saa7115 8-004a: It seems to be a gm7113c chip (10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10) @ 0x94.
saa7115 8-004a: gm7113c found @ 0x94 (smi2021)
```
So your chip is giving another id, and the saa7115 driver doesn't recognize it.

The saa7115 driver is trying to autodetect the i2c chip.
I think you can change one of the i2c lines in smi2021_main so we don't do autodetection, but specify gm7113c.

The best would be to patch this error in saa7115

**Comment by mastervolkov** [comment]
1. @jonjonarnearne can you path these error(send patch to kenel)?
2. For the future we can add option to module smi2021 with force set gm7113c in i2c

**Comment by jonjonarnearne** [comment]
Can you open your device and tell me what chip it contains?
Maybe it's a genuine saa7113, or some other chip that the saa7115 driver already can handle?

**Comment by mastervolkov** [comment]
I can only say after 17.08.
But in branch `force_init_option` already add needed code for parameters, but i dont know what (in which registry) write for owerride autodetection ...

**Comment by mastervolkov** [comment]
As i see in drivers/media/i2c/saa7115.c
saa711x_detect_chip *must* return GM7113C, otherwise no way skip `1930: if (state->ident > SAA7111A && state->ident != GM7113C)`

**Comment by mastervolkov** [comment]
As temporary override these issue we can apply patch for force detect our chip:
```
--- linux-old/drivers/media/i2c/saa7115.c  2014-12-08 01:21:05.000000000 +0300
+++ linux/drivers/media/i2c/saa7115.c 2015-08-14 13:36:49.000000000 +0300
@@ -1755,7 +1755,7 @@ static int saa711x_detect_chip(struct i2
        }
 
        /* Check if it is a gm7113c */
-       if (!memcmp(name, "0000", 4)) {
+       if (!memcmp(name, "0000", 4) || !memcmp(name, "1111", 4)) {
                chip_id = 0;
                for (i = 0; i < 4; i++) {
                        chip_id = chip_id << 1;
```

**Comment by mastervolkov** [comment]
Added code in `staging` branch for override cip version.
smi2021 module parameter `forceasgm`.
And some new warning about supported or not current chip.

**Comment by mastervolkov** [comment]
> Can you open your device and tell me what chip it contains?

SAA7113H
https://img.ie/image/gtV

**Comment by jonjonarnearne** [comment]
Great,
then maybe we should change the driver so it registers as regular saa7113 instead of gm7113c if it encounters a device that isn't gm7113c?

I believe that is a more correct solution to this problem :)

**Comment by mastervolkov** [comment]
Yes, but how set chip in i2c as saa7113?
And how detect - what chip gm or saa with register read?

чт, 20 авг. 2015, 21:13, Jon Arne Jørgensen <notifications@github.com>:

**Comment by jonjonarnearne** [comment]
I don't have time to hack on this right now, and I don't have the other device to debug.
But I believe that in smi2021_main.c, you will have to change these function calls:
`
	strlcpy(smi2021->gm7113c_info.type, "gm7113c",
					sizeof(smi2021->gm7113c_info.type));

	smi2021->gm7113c_subdev = v4l2_i2c_new_subdev_board(&smi2021->v4l2_dev,
							&smi2021->i2c_adap,
							&smi2021->gm7113c_info, NULL);
`
We should probably have another struct like the `gm7113c_info`, but renamed `saa7115_info`.
The saa7115 struct could probably be a lot simpler than the `gm7113c_info` struct as it probably doesn't need as much override functions.

I don't remeber the details about these structs, but i think the `v4l2_i2c_new_subdev_board` function can be replaced with a simpler one that don't need the struct, only the name of the i2c chip you intend to support?

Also, I think the driver could be changed to check if it successfully connected to gm7113c - (I'm not sure how to check this, but it should be possible) - and then, if that connection fails, try to connect saa7113.

As I said, I'm sorry that I don't have the time to hack at this, but if I find the time I'll notify you :)

**Comment by mastervolkov** [comment]
I think I found something interesting.

in smi2021_main.c on function smi2021_i2c_xfer
`Write reg` on 0x4a in 0x00 not write parameter (simple break if 0x00), but if you write - you can read not only version :) 
In my case - i read `1f7113d` and saa7115 module print
```
saa7115 0-004a: found saa7113 while gm7113c was expected
```
tomorrow i try hack more.

**Comment by mastervolkov** [comment]
Add these change and some debug to `feature_proper_chip_detect` branch.
Can anybody test and send new messages from dmesg (from smi2021) module?

**Comment by mastervolkov** [comment]
One bug/problem present (`feature_proper_chip_detect`):

When i do (not only in smi2021, but that code in saa7115 too):
```
#define CHIP_VER_SIZE   16
...
char chip_ver[CHIP_VER_SIZE + 1];

    for (i = 0; i < CHIP_VER_SIZE; i++) {
        smi2021_set_reg(smi2021, 0x4a, 0x00, i);
        smi2021_get_reg(smi2021, 0x4a, 0x00, &rrbuf);
        chip_ver[i] = (rrbuf & 0x0f) + '0';
        if (chip_ver[i] > '9')
            chip_ver[i] += 'a' - '9' - 1;
    }
```
`dev_warn(dev, " You chip is: %s \n", chip_ver);` not allways return `1f7113`.
because of this, in smi2021 i unable detect version and/or in saa7115 version can't detect correct.

**Comment by mastervolkov** [comment]
Also i have bcdDevice = 0100 - anybody have other?

**Comment by mastervolkov** [comment]
Anybody with gm711C chip can check and write what is in the lines **`try detect for:`** in `chip_detecting_fix_and_override` branch?

**Comment by mastervolkov** [comment]
Now, sometimes, saa7115.ko detects the chip correctly.
Problem in detection due to the #18
