### ISSUE TITLE
Kerneltree version 3.10.80 howto?

### ISSUE THREAD

**Issue by git2212** [Manouchehri/smi2021#25]
Hello,

I need to add support for the Somagic device to a kernel which is version 3.10.80. As the minimum baseline for the current version of the smi2021 is 3.12 this code fails to compile.

What can be done to add support for the kernel tree at https://github.com/XeoSal/linux?

Thank you.

**Comment by mastervolkov** [comment]
You can add support themselves for detailed instructions and links to the appropriate patches can be obtained from https://github.com/Manouchehri/smi2021/wiki/BuildingKernelModule#add-supporting-modules

**Comment by git2212** [comment]
I've applied the patches 1-6 from the above link. That is not sufficient as the kernel version seems to be an issue during compile as well. Is there a version of this driver which works with the 3.10 kernel?

Thx

**Comment by mastervolkov** [comment]
I don't test that driver in kernel version earlier 3.12. But, if you apply all 1-6 patches, you can *disable* version check:
Simple remove from smi2021_main.c string 40-42:
```
#if LINUX_VERSION_CODE < KERNEL_VERSION(3, 12, 0)
# error We only support 3.12 and above series kernels
#endif
```
If all patch apply correct - all will be work correct too.
