### ISSUE TITLE
module won't compile on Arch linux

### ISSUE THREAD

**Issue by paulscottrobson** [Manouchehri/smi2021#30]
the line .queue_setup = queue_setup doesn't work. smi2021_v4l2.c ; changing i so queue_setup is cast to a void pointer before assignment seems to fix it successfully ; I presule this is a compiler change ?

**Comment by NBonaparte** [comment]
I have found the change which caused the issue. [This commit](https://github.com/torvalds/linux/commit/36c0f8b32c4bd4f668cedfba6d97afaa84f055fb) on `videobuf2-core.h` changes `void *alloc_ctxs[]` to `struct device *alloc_devs[]`; performing the same change on `smi2021_v4l2.c` should fix this problem.
